### ISSUE TITLE
Typo错误

### ISSUE THREAD

**Issue by iphyer** [larrycai/sdcamp#18]
第四章《如何写好Java程序》中第二段开头，“首先你要有想把代码写好的意识，否者再怎么说都没用。”这里是“否则”吧?
Typo错误。

**Comment by larrycai** [comment]
是的，谢谢

**Comment by larrycai** [comment]
@iphyer the latest pdf is available https://drone.io/github.com/larrycai/sdcamp/files/sdcamp.pdf

**Comment by iphyer** [comment]
OK！
wonderful！
